### ISSUE TITLE
Separate .so files for app and service

### ISSUE THREAD

**Issue by me21** [bbernhard/qtandroidservices_example#3]
Can you please build an example showing how to make separate .so files for app and service?

**Comment by bbernhard** [comment]
Unfortunately, I haven't done much with Qt lately. But it shouldn't be that hard to accomplish that with Qt..see also this article here: https://www.kdab.com/qt-android-create-android-service-using-qt/

In the section "Separate .so files for app & service(s)" the author describes how you can create different *so files with Qt. I haven't followed the android related development of Qt lately...so maybe there is even an easier way to accomplish that now. In case you have any questions, the Qt mailing list is always a good starting point: https://lists.qt-project.org/listinfo/interest

The author of the article above, Bogdan Vatra, who is btw. also a major contributor to the Qt Android port is btw. also on that list. So chances are high, that someone can help you there :)

**Comment by me21** [comment]
Thanks! There is a link to a repo at the end of that article. I'll post it here for future reference: https://github.com/KDAB/android

It contains Android service implementation for separate .so app and service files.

So whoever needs common .so file, may use your repo, and whoever needs separate .so files, may use their repo :)
